"""
Business Operations MCP Server + Assistant
===========================================

A small business domain (customers / orders / support tickets / refunds)
exposed through an MCP (Model Context Protocol) server, plus a tiny
assistant that uses those tools, with a consent/approval gate in front of
the one side-effecting action (process_refund).

Run:
    pip install -r requirements.txt
    cp .env.example .env        # (optional) add your AI_API_KEY
    uvicorn main:app --reload --port 8000

Docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""

import json
import os
import re
import uuid
from datetime import date
from typing import Any, Optional

import httpx
from dotenv import load_dotenv
from fastapi import Depends, FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from data import CUSTOMERS, ORDERS, REFUNDS, TICKETS

load_dotenv()

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
AI_BASE_URL = os.getenv("AI_BASE_URL", "https://ai.nik6348.in/v1").rstrip("/")
AI_API_KEY = os.getenv("AI_API_KEY", "").strip()
AI_MODEL = os.getenv("AI_MODEL", "gemini-pro")
MCP_API_KEY = os.getenv("MCP_API_KEY", "dev-local-key-123")

app = FastAPI(title="Business Operations MCP Server", version="1.0.0")

# The frontend runs on localhost:5173 (vite). In production, replace this
# with your real domain. See README "Auth / deployment" section.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Authentication / Authorization
# ---------------------------------------------------------------------------
def require_api_key(x_api_key: str = Header(default="")) -> None:
    """Every MCP + business API call must present the X-API-Key header.

    Scope (documented): this default key is a LOCAL-ONLY development key.
    For remote deployment set a strong MCP_API_KEY env var and serve only
    over HTTPS — see README.md, section "Auth / deployment".
    """
    if x_api_key != MCP_API_KEY:
        raise HTTPException(status_code=401, detail="Invalid or missing X-API-Key header")


# ---------------------------------------------------------------------------
# The business domain (what the MCP tools operate on)
# ---------------------------------------------------------------------------
def find_customer(query: str) -> list[dict]:
    """Fuzzy search customers by name, email, phone or id."""
    q = query.lower().strip()
    return [
        c for c in CUSTOMERS
        if q in c["name"].lower() or q in c["email"].lower()
        or q in c["phone"].lower() or q in c["id"].lower() or q in c["city"].lower()
    ]


def orders_of(customer_id: str) -> list[dict]:
    return [o for o in ORDERS if o["customer_id"] == customer_id]


def orders_of_any(customer_ids: list[str]) -> list[dict]:
    return [o for o in ORDERS if o["customer_id"] in customer_ids]


# ---------------------------------------------------------------------------
# Approval store — the consent gate for side-effecting calls
# ---------------------------------------------------------------------------
APPROVALS: dict[str, dict] = {}


def create_approval(action: str, params: dict, summary: str) -> dict:
    appr_id = "APR-" + uuid.uuid4().hex[:8].upper()
    params_copy = dict(params)
    params_copy["approval_id"] = appr_id
    approval = {
        "approval_id": appr_id,
        "action": action,
        "params": params_copy,
        "summary": summary,
        "status": "pending",        # pending -> approved | rejected | used
        "created_at": str(date.today()),
    }
    APPROVALS[approval["approval_id"]] = approval
    return approval


# ---------------------------------------------------------------------------
# MCP tool registry — each tool has a clear description + JSON input schema
# ---------------------------------------------------------------------------
TOOLS = [
    {
        "name": "search_customers",
        "description": "Search customers by name, email, phone, customer ID or city. Read-only, safe to call any time.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "Name, email, phone, ID or city to search for"}
            },
            "required": ["query"],
        },
    },
    {
        "name": "read_orders",
        "description": "Read the order history for one or more customers. Read-only, safe to call any time.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "customer_ids": {"type": "array", "items": {"type": "string"}, "description": "List of customer IDs, e.g. [\"CUST-001\"]"}
            },
            "required": ["customer_ids"],
        },
    },
    {
        "name": "create_support_ticket",
        "description": "Create a support ticket for a customer. Low-risk action; every ticket is logged.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "customer_id": {"type": "string", "description": "Customer ID, e.g. CUST-001"},
                "subject": {"type": "string", "description": "Short subject line"},
                "description": {"type": "string", "description": "What is the issue?"},
                "priority": {"type": "string", "enum": ["low", "medium", "high"], "description": "Ticket priority"},
            },
            "required": ["customer_id", "subject", "description", "priority"],
        },
    },
    {
        "name": "process_refund",
        "description": "APPROVAL-REQUIRED side effect: move money back to a customer. Can only run with a valid, user-approved approval_id created through the consent gate (POST /api/approvals). The approval is single-use.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "order_id": {"type": "string", "description": "Order to refund, e.g. ORD-1003"},
                "amount": {"type": "number", "description": "Amount in INR to refund"},
                "reason": {"type": "string", "description": "Why the refund is being given"},
                "approval_id": {"type": "string", "description": "Consent token from the approval gate"},
            },
            "required": ["order_id", "amount", "reason", "approval_id"],
        },
    },
]

# MCP resources (read-only data exposed as URIs)
RESOURCES = [
    {
        "uri": "business://metrics/summary",
        "name": "Store summary metrics",
        "description": "Total customers, orders, revenue and open tickets as JSON.",
        "mimeType": "application/json",
    },
    {
        "uri": "business://policies/refund",
        "name": "Refund policy",
        "description": "Plain-text refund policy document.",
        "mimeType": "text/plain",
    },
]

# MCP reusable prompt templates
PROMPTS = [
    {
        "name": "support-reply-drafter",
        "description": "Draft a polite, professional support reply for a customer issue.",
        "arguments": [
            {"name": "customer_name", "description": "Customer's name", "required": True},
            {"name": "issue", "description": "The customer's problem in one sentence", "required": True},
            {"name": "resolution", "description": "What we will do about it", "required": True},
        ],
    },
    {
        "name": "refund-approval-explainer",
        "description": "Explain a pending refund approval to a human reviewer before they consent.",
        "arguments": [
            {"name": "order_id", "description": "Order being refunded", "required": True},
            {"name": "amount", "description": "Refund amount in INR", "required": True},
            {"name": "reason", "description": "Refund reason", "required": True},
        ],
    },
]


def store_summary() -> dict:
    revenue = sum(o["amount"] for o in ORDERS if o["status"] == "delivered")
    return {
        "total_customers": len(CUSTOMERS),
        "total_orders": len(ORDERS),
        "revenue_delivered_orders_inr": revenue,
        "open_tickets": len([t for t in TICKETS if t["status"] in ("open", "in_progress")]),
        "refunds_processed": len(REFUNDS),
    }


def call_tool(name: str, arguments: dict) -> dict:
    """Execute one MCP tool. Returns {"ok": ..., "result"/"error": ...}."""
    if name == "search_customers":
        matches = find_customer(arguments.get("query", ""))
        return {"ok": True, "result": matches}

    if name == "read_orders":
        ids = arguments.get("customer_ids", [])
        return {"ok": True, "result": orders_of_any(ids)}

    if name == "create_support_ticket":
        cid = arguments["customer_id"]
        if not any(c["id"] == cid for c in CUSTOMERS):
            return {"ok": False, "error": f"Unknown customer_id: {cid}"}
        ticket = {
            "id": "TKT-" + str(9000 + len(TICKETS) + 1),
            "customer_id": cid,
            "subject": arguments["subject"],
            "description": arguments["description"],
            "priority": arguments["priority"],
            "status": "open",
            "created_at": str(date.today()),
        }
        TICKETS.append(ticket)
        return {"ok": True, "result": ticket}

    if name == "process_refund":
        # ---- THE CONSENT GATE ----
        approval_id = arguments.get("approval_id", "")
        approval = APPROVALS.get(approval_id)
        if not approval or approval["status"] != "approved":
            return {"ok": False, "error": "Missing or invalid approval. Side-effecting calls require a user-approved, single-use approval_id from POST /api/approvals."}
        order = next((o for o in ORDERS if o["id"] == arguments["order_id"]), None)
        if not order:
            return {"ok": False, "error": f"Unknown order_id: {arguments['order_id']}"}
        if arguments["amount"] <= 0 or arguments["amount"] > order["amount"]:
            return {"ok": False, "error": f"Amount must be between 1 and {order['amount']} INR for this order."}
        approval["status"] = "used"  # single-use: burn the token
        refund = {
            "id": "RFD-" + uuid.uuid4().hex[:6].upper(),
            "order_id": order["id"],
            "customer_id": order["customer_id"],
            "amount": arguments["amount"],
            "reason": arguments["reason"],
            "approval_id": approval_id,
            "processed_at": str(date.today()),
        }
        REFUNDS.append(refund)
        order["status"] = "refunded"
        return {"ok": True, "result": refund}

    return {"ok": False, "error": f"Unknown tool: {name}"}


# ---------------------------------------------------------------------------
# MCP protocol endpoint (JSON-RPC 2.0)
# ---------------------------------------------------------------------------
class McpRequest(BaseModel):
    jsonrpc: str = "2.0"
    id: Any = 1
    method: str
    params: Optional[dict] = None


@app.post("/mcp", dependencies=[Depends(require_api_key)])
def mcp_endpoint(req: McpRequest) -> dict:
    """Minimal MCP server: initialize, tools/list, tools/call, resources, prompts."""
    params = req.params or {}

    if req.method == "initialize":
        return {"jsonrpc": "2.0", "id": req.id, "result": {
            "protocolVersion": "2024-11-05",
            "capabilities": {"tools": {}, "resources": {}, "prompts": {}},
            "serverInfo": {"name": "business-operations-mcp", "version": "1.0.0"},
        }}

    if req.method == "tools/list":
        return {"jsonrpc": "2.0", "id": req.id, "result": {"tools": TOOLS}}

    if req.method == "tools/call":
        outcome = call_tool(params.get("name", ""), params.get("arguments", {}))
        if not outcome["ok"]:
            return {"jsonrpc": "2.0", "id": req.id, "result": {
                "content": [{"type": "text", "text": outcome["error"]}], "isError": True}}
        return {"jsonrpc": "2.0", "id": req.id, "result": {
            "content": [{"type": "text", "text": json.dumps(outcome["result"], indent=2)}], "isError": False}}

    if req.method == "resources/list":
        return {"jsonrpc": "2.0", "id": req.id, "result": {"resources": RESOURCES}}

    if req.method == "resources/read":
        uri = params.get("uri", "")
        if uri == "business://metrics/summary":
            text = json.dumps(store_summary(), indent=2)
        elif uri == "business://policies/refund":
            text = ("Refund policy:\n1. Refunds are allowed within 30 days of delivery.\n"
                    "2. Amount must not exceed the paid amount of the order.\n"
                    "3. Every refund requires explicit human approval via the consent gate.\n"
                    "4. Approved refunds complete in 3-5 business days.")
        else:
            return {"jsonrpc": "2.0", "id": req.id, "result": {
                "contents": [], "isError": True}}
        return {"jsonrpc": "2.0", "id": req.id, "result": {
            "contents": [{"uri": uri, "mimeType": "text/plain", "text": text}]}}

    if req.method == "prompts/list":
        return {"jsonrpc": "2.0", "id": req.id, "result": {"prompts": PROMPTS}}

    if req.method == "prompts/get":
        name = params.get("name", "")
        args = params.get("arguments", {})
        if name == "support-reply-drafter":
            prompt_text = (
                f"Write a short, polite support reply.\n"
                f"Customer: {args.get('customer_name', '')}\n"
                f"Issue: {args.get('issue', '')}\n"
                f"Resolution: {args.get('resolution', '')}\n"
                f"Tone: empathetic, professional, under 120 words."
            )
        elif name == "refund-approval-explainer":
            prompt_text = (
                f"Explain this refund request to a human approver in 3 bullet points:\n"
                f"Order: {args.get('order_id', '')}\n"
                f"Amount: ₹{args.get('amount', '')}\n"
                f"Reason: {args.get('reason', '')}\n"
                f"Include one line about the risks of approving vs rejecting."
            )
        else:
            return {"jsonrpc": "2.0", "id": req.id, "result": {"isError": True}}
        return {"jsonrpc": "2.0", "id": req.id, "result": {
            "messages": [{"role": "user", "content": {"type": "text", "text": prompt_text}}]}}

    return {"jsonrpc": "2.0", "id": req.id, "error": {"code": -32601, "message": f"Method not found: {req.method}"}}


# ---------------------------------------------------------------------------
# Consent / approval REST API (used by the frontend modal)
# ---------------------------------------------------------------------------
class ApprovalRequest(BaseModel):
    action: str = "process_refund"
    order_id: str
    amount: float
    reason: str


@app.post("/api/approvals", dependencies=[Depends(require_api_key)])
def request_approval(body: ApprovalRequest) -> dict:
    """Step 1 of the consent gate: a human must approve before the side effect runs."""
    order = next((o for o in ORDERS if o["id"] == body.order_id), None)
    if not order:
        raise HTTPException(404, f"Order {body.order_id} not found")
    customer = next(c for c in CUSTOMERS if c["id"] == order["customer_id"])
    summary = f"Refund ₹{body.amount:g} to {customer['name']} for order {body.order_id} ({order['item']}). Reason: {body.reason}"
    approval = create_approval(body.action, body.model_dump(), summary)
    return approval


class ApprovalDecision(BaseModel):
    note: str = ""


@app.post("/api/approvals/{approval_id}/approve", dependencies=[Depends(require_api_key)])
def approve_and_execute(approval_id: str, body: ApprovalDecision) -> dict:
    """Step 2: human consented -> execute the side-effecting MCP tool once."""
    approval = APPROVALS.get(approval_id)
    if not approval:
        raise HTTPException(404, "Approval not found")
    if approval["status"] != "pending":
        raise HTTPException(409, f"Approval already {approval['status']}")
    approval["status"] = "approved"  # unlock the tool for one call
    params = dict(approval["params"])
    params["approval_id"] = approval_id
    outcome = call_tool(approval["action"], params)
    approval["note"] = body.note
    if not outcome["ok"]:
        approval["status"] = "rejected"  # tool refused: roll the gate back
        raise HTTPException(422, outcome["error"])
    return {"approval": approval, "result": outcome["result"]}


@app.post("/api/approvals/{approval_id}/reject", dependencies=[Depends(require_api_key)])
def reject_approval(approval_id: str, body: ApprovalDecision) -> dict:
    approval = APPROVALS.get(approval_id)
    if not approval:
        raise HTTPException(404, "Approval not found")
    approval["status"] = "rejected"
    approval["note"] = body.note
    return approval


@app.get("/api/approvals", dependencies=[Depends(require_api_key)])
def list_approvals() -> list[dict]:
    return list(APPROVALS.values())


# ---------------------------------------------------------------------------
# Plain REST helpers for the frontend panels
# ---------------------------------------------------------------------------
@app.get("/api/health")
def health() -> dict:
    return {"status": "ok", "ai_configured": bool(AI_API_KEY)}


@app.get("/api/customers", dependencies=[Depends(require_api_key)])
def api_customers(q: str = "") -> list[dict]:
    return find_customer(q) if q else CUSTOMERS


@app.get("/api/customers/{customer_id}/orders", dependencies=[Depends(require_api_key)])
def api_customer_orders(customer_id: str) -> list[dict]:
    return orders_of(customer_id)


@app.get("/api/metrics", dependencies=[Depends(require_api_key)])
def api_metrics() -> dict:
    return store_summary()


@app.get("/api/orders", dependencies=[Depends(require_api_key)])
def api_orders() -> list[dict]:
    return ORDERS


@app.get("/api/tickets", dependencies=[Depends(require_api_key)])
def api_tickets() -> list[dict]:
    return TICKETS


@app.get("/api/refunds", dependencies=[Depends(require_api_key)])
def api_refunds() -> list[dict]:
    return REFUNDS


@app.get("/api/tools", dependencies=[Depends(require_api_key)])
def api_tools() -> list[dict]:
    return TOOLS


@app.get("/api/resources", dependencies=[Depends(require_api_key)])
def api_resources() -> list[dict]:
    return RESOURCES


@app.get("/api/prompts", dependencies=[Depends(require_api_key)])
def api_prompts() -> list[dict]:
    return PROMPTS


# ---------------------------------------------------------------------------
# The assistant — routes user text to MCP tools, then (optionally) phrases
# the answer with the configured AI service.
# ---------------------------------------------------------------------------
class ChatRequest(BaseModel):
    message: str


async def ask_ai(user_message: str, tool_context: str) -> Optional[str]:
    """Call the configured OpenAI-compatible chat endpoint. None if unavailable."""
    if not AI_API_KEY:
        return None
    system = (
        "You are BusinessOps Assistant, a friendly support assistant for a small electronics store. "
        "You can search customers, read orders, create support tickets, and process refunds (with human approval). "
        "Keep answers short (under 100 words). Tool data:\n" + tool_context
    )
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                f"{AI_BASE_URL}/chat/completions",
                headers={"Authorization": f"Bearer {AI_API_KEY}", "Content-Type": "application/json"},
                json={"model": AI_MODEL, "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": user_message},
                ]},
            )
            resp.raise_for_status()
            return resp.json()["choices"][0]["message"]["content"]
    except Exception:
        return None  # fall back to built-in reply so the demo never breaks


def extract_name(text: str) -> Optional[str]:
    """Best-effort: pull 'for X' / 'of X' / 'customer X' out of a message."""
    m = re.search(r"(?:for|of|customer)\s+([A-Za-z]+)", text, re.IGNORECASE)
    return m.group(1) if m else None


@app.post("/api/chat", dependencies=[Depends(require_api_key)])
async def chat(body: ChatRequest) -> dict:
    msg = body.message.strip()
    lower = msg.lower()
    tool_context = ""

    # --- Intent 1: refund (the guarded side effect) -------------------------
    if "refund" in lower:
        m = re.search(r"ord-\d+", lower)
        amt = re.search(r"₹?\s*(\d+(?:\.\d+)?)", msg)
        order_id = m.group(0).upper() if m else None
        amount = float(amt.group(1)) if amt else None
        if not order_id or amount is None:
            text = ("To process a refund, tell me: order ID and amount.\n"
                    "Example: *refund ₹500 for ORD-1008 because item was damaged*\n"
                    "You will be asked to approve it before any money moves.")
            ai = await ask_ai(msg, text)
            return {"type": "message", "text": ai or text}
        reason = msg.split("because")[-1].strip() if "because" in lower else "requested by customer"
        approval = request_approval(ApprovalRequest(order_id=order_id, amount=amount, reason=reason))
        return {"type": "approval_required", "approval": approval,
                "text": f"I've prepared a refund of ₹{amount:g} for {order_id}. Please review and approve it below."}

    # --- Intent 2: create a support ticket ----------------------------------
    if "ticket" in lower and any(w in lower for w in ("create", "raise", "file", "open")):
        name = extract_name(msg)
        matches = find_customer(name) if name else []
        if not matches:
            text = ("Sure — which customer is the ticket for?\n"
                    "Example: *create ticket for Priya about laptop stand is broken, priority high*")
            return {"type": "message", "text": text}
        priority = "high" if "high" in lower else "low" if "low" in lower else "medium"
        about = re.sub(r"(?i)create ticket for \w+ (about|regarding)?\s*", "", msg).strip()
        outcome = call_tool("create_support_ticket", {
            "customer_id": matches[0]["id"], "subject": about[:80] or "General issue",
            "description": about or "No details provided.", "priority": priority})
        ticket = outcome["result"]
        tool_context = json.dumps(ticket)
        text = (f"Ticket {ticket['id']} created for {matches[0]['name']} ✅\n"
                f"Subject: {ticket['subject']}\nPriority: {ticket['priority']}")
        ai = await ask_ai(msg, tool_context)
        return {"type": "message", "text": ai or text}

    # --- Intent 3: read orders ----------------------------------------------
    if "order" in lower and any(w in lower for w in ("show", "list", "read", "get", "what")):
        name = extract_name(msg)
        matches = find_customer(name) if name else []
        if not matches:
            text = "Whose orders should I look up? Example: *show orders of Priya*"
            return {"type": "message", "text": text}
        rows = orders_of_any([c["id"] for c in matches])
        tool_context = json.dumps(rows)
        if not rows:
            text = f"No orders found for {matches[0]['name']}."
        else:
            lines = [f"• {o['id']} — {o['item']} — ₹{o['amount']:,} — {o['status']} ({o['date']})" for o in rows]
            text = f"Orders of {matches[0]['name']}:\n" + "\n".join(lines)
        ai = await ask_ai(msg, tool_context)
        return {"type": "message", "text": ai or text}

    # --- Intent 4: search customers ------------------------------------------
    if any(w in lower for w in ("customer", "search", "find", "who is")):
        name = extract_name(msg) or re.sub(r"(?i)(search|find|customer|for|who is)\s*", "", msg).strip()
        matches = find_customer(name) if name else []
        tool_context = json.dumps(matches)
        if not matches:
            text = f"No customer matched '{name}'. Try a name, city or email."
        else:
            lines = [f"• {c['id']} — {c['name']} ({c['tier']}) — {c['city']} — {c['email']}" for c in matches]
            text = f"Found {len(matches)} customer(s):\n" + "\n".join(lines)
        ai = await ask_ai(msg, tool_context)
        return {"type": "message", "text": ai or text}

    # --- Fallback: general question / help ------------------------------------
    help_text = ("I can help with:\n"
                 "• *find customer Priya*\n"
                 "• *show orders of Rohan*\n"
                 "• *create ticket for Aarav about mouse not working, priority high*\n"
                 "• *refund ₹500 for ORD-1008 because item was damaged* (needs your approval)")
    tool_context = json.dumps(store_summary())
    ai = await ask_ai(msg, tool_context)
    return {"type": "message", "text": ai or help_text}
